### ISSUE TITLE
Invalid Predicate Error When Getting Packages

### ISSUE THREAD

**Issue by ysiadf** [dimitri/emacs-kicker#3] opened 2011-09-05 08:52 UTC
Due to the error getting emacs-goodies, I've commented out the lines:

(when (el-get-executable-find "cvs")
  (add-to-list 'my:el-get-packages 'emacs-goodies-el))

Now the file runs until:
(el-get 'sync my:el-get-packages) ;line 83

At that point, it throws an invalid predicate error.

**Comment by dimitri** [comment] 2011-09-05 18:06
Could you paste the errors you have?  Try emacs --debug-init to get a trace, or M-x toggle-debug-on-error. Thanks!

**Comment by ysiadf** [comment] 2011-09-06 07:48
Errors below. I ran the emacs-kicker.el file buffer https://gist.github.com/1196876 and the following was the debug statement.

``` emacslisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  insert-file-contents(nil nil nil nil nil)
  insert-file-contents-literally(nil)
  el-get-read-recipe-file(nil)
  el-get-read-recipe("nil")
  el-get-package-def("nil")
  el-get-error-unless-package-p("nil")
  el-get-install("nil")
  el-get-install-or-init("buffer-move" (:el-get "installed" :yasnippet "required" :psvn "installed" :emacs-goodies-el "required" :escreen "installed" :php-mode-improved "installed" :switch-window "installed" :auto-complete "installed" :zencoding-mode "installed" :color-theme "installed" :color-theme-tango "installed"))
  #[(s) "\302  \"\207" [s p-status el-get-install-or-init] 3]("buffer-move")
  mapc(#[(s) "\302 \"\207" [s p-status el-get-install-or-init] 3] (yasnippet psvn el-get escreen php-mode-improved switch-window auto-complete zencoding-mode color-theme color-theme-tango "buffer-move" "smex" "magit" "goto-last-change"))
  el-get(sync (yasnippet psvn el-get escreen php-mode-improved switch-window auto-complete zencoding-mode color-theme color-theme-tango "buffer-move" "smex" "magit" "goto-last-change"))
  eval-buffer()  ; Reading at buffer position 2689
  call-interactively(eval-buffer t nil)
  execute-extended-command(nil)
  call-interactively(execute-extended-command nil nil)
```

**Comment by seanfisk** [comment] 2011-09-09 08:22
Just had this error, took me a whale of a time trying to figure it out. This helped fix some of my sources, but not all for some reason:

``` emacslisp
(setq my:el-get-packages
      (append
       my:el-get-packages
       (loop for src in el-get-sources collect (make-symbol (el-get-source-name src)))))
```

Dimitri, it appears to me el-get is no longer OK with package names as strings. Basically, the little luck I had was converting them to symbols. But it's late so I could be totally wrong.

**Comment by dimitri** [comment] 2011-09-13 16:23
It seems your impression is confirmed by bug reporting on el-get.  I'm now wondering about either fixing 2.stable branch or releasing 3.1 from stable and working code in "master" branch.

**Comment by seanfisk** [comment] 2011-09-13 17:12
Totally personally, I'd prefer a 3.1 release of el-get. I've been on `master` since you pushed the fix to the installer, and I'd rather be on a stable version. But ultimately it's up to you. Thanks, Dimitri.

**Comment by dimitri** [comment] 2011-09-15 20:37
el-get 3.1 is now released!

**Closed as completed by dimitri** 2011-09-15 20:37 UTC
